### ISSUE TITLE
CONTRIBUTING.md file Missing

### ISSUE THREAD

**Issue by devaniketh** [MuhammedAdelTaha/8-Puzzle-AI-Solver#2]
- **First and foremost there's no CONTRIBUTING.md in this repository **]
- People will be confused on what to contribute
- So its recomended to add the required file ASAP ;)

**Comment by AnikethDeb2004** [comment]
**how can you even closed it before adding the file??**

**Comment by AnikethDeb2004** [comment]
Then please give me the access to upload it it would be great number in my contribution ?

**Comment by MuhammedAdelTaha** [comment]
No problem
